package hello.controller;

import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.security.core.context.SecurityContextHolder;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.ModelAttribute;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestParam;

import hello.model.Msg;
import hello.model.SysUser;
import hello.model.AttachFiles;


import hello.repository.AttachFilesRepository;

@Controller
public class HomeController {

	@Autowired // This means to get the bean called userRepository
	// Which is auto-generated by Spring, we will use it to handle the data
	private AttachFilesRepository filesRepository;


	@GetMapping("/")
	public String index(Model model)
	{

		SysUser principal =  (SysUser) SecurityContextHolder.getContext().getAuthentication().getPrincipal();

		String id =principal.getId().toString();

		List<AttachFiles> files =filesRepository.findByObjectIdAndObjectType(id, "user");

		model.addAttribute("files", files);


		Msg msg = new Msg("测试标题", "测试内容", "额外信息，只对管理员显示");
        model.addAttribute("msg", msg);
        return "index";

	}

	
	
	
}
